<a href="https://colab.research.google.com/github/kamillfo333/LLL/blob/main/firstLec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Basic 5

In [10]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Оригинальный массив")
print(a)
print("Проверьте заданный массив поэлементно на конечность :")
print(np.isfinite(a))

Оригинальный массив
[ 1.  0. nan inf]
Проверьте заданный массив поэлементно на конечность :
[ True  True False False]


15

In [11]:
import numpy as np
array=np.arange(30,71,2)
print("Массив всех четных целых чисел от 30 до 70")
print(array) 

Массив всех четных целых чисел от 30 до 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


25

In [12]:
import numpy as np
m= np.arange(10,22).reshape((3, 4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


35

In [13]:
import numpy as np
import os
a = np.arange(20)
np.save('temp_arra.npy', a)
print(" Проверьте, существует ли temp_arra.npy или нет?")
if os.path.exists('temp_arra.npy'):
    x2 = np.load('temp_arra.npy')
    print(np.array_equal(a, x2))

 Проверьте, существует ли temp_arra.npy или нет?
True


NumPy: упражнения с массивом
5