<a href="https://colab.research.google.com/github/kamillfo333/LLL/blob/main/firstLec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Basic 5

In [ ]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Оригинальный массив")
print(a)
print("Проверьте заданный массив поэлементно на конечность :")
print(np.isfinite(a))

Оригинальный массив
[ 1.  0. nan inf]
Проверьте заданный массив поэлементно на конечность :
[ True  True False False]


15

In [ ]:
import numpy as np
array=np.arange(30,71,2)
print("Массив всех четных целых чисел от 30 до 70")
print(array) 

Массив всех четных целых чисел от 30 до 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


25

In [ ]:
import numpy as np
m= np.arange(10,22).reshape((3, 4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


35

In [ ]:
import numpy as np
import os
a = np.arange(20)
np.save('temp_arra.npy', a)
print(" Проверьте, существует ли temp_arra.npy или нет?")
if os.path.exists('temp_arra.npy'):
    x2 = np.load('temp_arra.npy')
    print(np.array_equal(a, x2))

 Проверьте, существует ли temp_arra.npy или нет?
True


NumPy: упражнения с массивом
5

In [1]:
import numpy as np
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


15

In [2]:
import numpy as np
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print("Исходный массив:x ",x)
print("Исходный массив:y ",y)
print("Реальная часть массива:")
print(x.real)
print(y.real)
print("Мнимая часть массива:")
print(x.imag)
print(y.imag)

Исходный массив:x  [1.+0.j]
Исходный массив:y  [0.70710678+0.70710678j]
Реальная часть массива:
[1.]
[0.70710678]
Мнимая часть массива:
[0.]
[0.70710678]


25

In [3]:
import numpy as np
a = [1, 2, 3, 4]
print("Оригинальный массив ")
print(a)
print("Повторяя 2 раза ")
x = np.tile(a, 2)
print(x)
print("Повторяя 3 раза ")
x = np.tile(a, 3)
print(x)

Оригинальный массив 
[1, 2, 3, 4]
Повторяя 2 раза 
[1 2 3 4 1 2 3 4]
Повторяя 3 раза 
[1 2 3 4 1 2 3 4 1 2 3 4]


35

In [4]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print("6 строк и 0 столбцов ")
print(x.shape)
y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 строки и 3 столбца ")
print(y)
x = np.array([1,2,3,4,5,6,7,8,9])
print("Изменить форму массива на (3, 3) -> 3 строки и 3 столбца  ")
x.shape = (3, 3)
print(x)

6 строк и 0 столбцов 
(6,)
(3, 3) -> 3 строки и 3 столбца 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Изменить форму массива на (3, 3) -> 3 строки и 3 столбца  
[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [5]:
import numpy as np
x = np.linspace(2.5, 6.5, 30)
print(x)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


55

In [6]:
import numpy as np
x = 10
print("Просматривайте входные данные как массивы как минимум с двумя измерениями:")
print(np.atleast_1d(x))
x = np.arange(4.0).reshape(2, 2)
print(np.atleast_1d(x))
print("Просматривайте входные данные как массивы как минимум с тремя измерениями:")
x =15
print(np.atleast_3d(x))
x = np.arange(3.0)
print(np.atleast_3d(x))

Просматривайте входные данные как массивы как минимум с двумя измерениями:
[10]
[[0. 1.]
 [2. 3.]]
Просматривайте входные данные как массивы как минимум с тремя измерениями:
[[[15]]]
[[[0.]
  [1.]
  [2.]]]


65

In [7]:
import numpy as np
x = np.array([[1.12, 2.0, 3.45], [2.33, 5.12, 6.0]], float) 
print("Original array:")
print(x)
print(2 in x)
print(0 in x)
print(6 in x)
print(2.3 in x)
print(5.12 in x)

Original array:
[[1.12 2.   3.45]
 [2.33 5.12 6.  ]]
True
False
True
False
True


75

In [11]:
import numpy as np
x = np.zeros((3,), dtype=('i4,f4,a40'))
new_data = [(1, 2., "Albert Einstein"), (2, 2., "Edmond Halley"), (3, 3., "Gertrude B. Elion")]
x[:] = new_data
print(x)


[(1, 2., b'Albert Einstein') (2, 2., b'Edmond Halley')
 (3, 3., b'Gertrude B. Elion')]


85

In [16]:
import numpy as np
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])
print(np.append(x, y, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


95

In [17]:
import numpy as np
x = np.array([2, 3])
y = np.array([])
# size 2, array is not empty
print(x.size)
# size 0, array is empty
print(y.size)

2
0


105

In [19]:
import numpy as np
nums = np.array([10, 20, 20, 20, 20, 0, 20, 30, 30, 30, 0, 0, 20, 20, 0])
print("Original array:")
print(nums)
print(np.count_nonzero(nums == 10))
print(np.count_nonzero(nums == 20))
print(np.count_nonzero(nums == 30))
print(np.count_nonzero(nums == 0))

Original array:
[10 20 20 20 20  0 20 30 30 30  0  0 20 20  0]
1
7
3
4


115

In [21]:
import numpy as np
nums = np.array([1,0,2,0,3,0,4,5,6,7,8])
print(" Исходный массив:")
print(nums)
print("Индексы элементов равны нулю указанного массива:")
result = np.where(nums == 0)[0]
print(result)

 Исходный массив:
[1 0 2 0 3 0 4 5 6 7 8]
Индексы элементов равны нулю указанного массива:
[1 3 5]


125

In [23]:
import numpy as np    
p = np.array([[0], [10], [20]]) 
q= np.array([10, 11, 12]) 
print("Оригинальные массивы:")
print("Массив-1")
print(p)
print("Массив-2")
print(q)
print("Новый массив:")
new_array1 = p + q 
print(new_array1)

Оригинальные массивы:
Массив-1
[[ 0]
 [10]
 [20]]
Массив-2
[10 11 12]
Новый массив:
[[10 11 12]
 [20 21 22]
 [30 31 32]]


135

In [24]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print(" Исходный массив:")
print(arra_data)
print("Извлеченные данные: второй ряд")
print(arra_data[1,:])

 Исходный массив:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Извлеченные данные: второй ряд
[4 5 6 7]


145

In [25]:
import numpy as np
arra_data = np.arange(0,36).reshape((6, 6))
print("Исходный массив:")
print(arra_data)
print("Извлеченные данные: первый, третий и пятый элементы третьего и пятого рядов")
print(arra_data[2::2, ::2]) 

Исходный массив:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
Извлеченные данные: первый, третий и пятый элементы третьего и пятого рядов
[[12 14 16]
 [24 26 28]]


155

In [26]:
import numpy as np
num = np.arange(20)
arr1 = np.reshape(num, [4, 5])
print(" Исходный массив:")
print(arr1)
print([0, 1, 2, 3, 4] in arr1.tolist())
print([0, 1, 2, 3, 5] in arr1.tolist())
print([15, 16, 17, 18, 19] in arr1.tolist())

 Исходный массив:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
True
False
True


Линейная алгебра

5

In [27]:
import numpy as np
a = np.array([1,2,3])
b = np.array([0,1,0])
print(" Оригинальные 1-й массивы:")
print(a)
print(b)
result =  np.einsum("n,n", a, b)
print("Соглашение Эйнштейна о суммировании указанных массивов:")
print(result)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Оригинал Высшее измерение:")
print(x)
print(y)
result = np.einsum("mk,kn", x, y)
print("Соглашение Эйнштейна о суммировании указанных массивов:")
print(result)

 Оригинальные 1-й массивы:
[1 2 3]
[0 1 0]
Соглашение Эйнштейна о суммировании указанных массивов:
2
Оригинал Высшее измерение:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Соглашение Эйнштейна о суммировании указанных массивов:
[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]


15

In [28]:
import numpy as np
m = np.arange(6).reshape(2,3)
print(" Исходная матрица:")
print(m)
result =  np.trace(m)
print("Номер условия указанной матрицы:")
print(result)

 Исходная матрица:
[[0 1 2]
 [3 4 5]]
Номер условия указанной матрицы:
4


Случайные упражнения

5