<a href="https://colab.research.google.com/github/kamillfo333/LLL/blob/main/firstLec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Basic 5

In [ ]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Оригинальный массив")
print(a)
print("Проверьте заданный массив поэлементно на конечность :")
print(np.isfinite(a))

Оригинальный массив
[ 1.  0. nan inf]
Проверьте заданный массив поэлементно на конечность :
[ True  True False False]


15

In [ ]:
import numpy as np
array=np.arange(30,71,2)
print("Массив всех четных целых чисел от 30 до 70")
print(array) 

Массив всех четных целых чисел от 30 до 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


25

In [ ]:
import numpy as np
m= np.arange(10,22).reshape((3, 4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


35

In [ ]:
import numpy as np
import os
a = np.arange(20)
np.save('temp_arra.npy', a)
print(" Проверьте, существует ли temp_arra.npy или нет?")
if os.path.exists('temp_arra.npy'):
    x2 = np.load('temp_arra.npy')
    print(np.array_equal(a, x2))

 Проверьте, существует ли temp_arra.npy или нет?
True


NumPy: упражнения с массивом
5

In [ ]:
import numpy as np
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


15

In [ ]:
import numpy as np
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print("Исходный массив:x ",x)
print("Исходный массив:y ",y)
print("Реальная часть массива:")
print(x.real)
print(y.real)
print("Мнимая часть массива:")
print(x.imag)
print(y.imag)

Исходный массив:x  [1.+0.j]
Исходный массив:y  [0.70710678+0.70710678j]
Реальная часть массива:
[1.]
[0.70710678]
Мнимая часть массива:
[0.]
[0.70710678]


25

In [ ]:
import numpy as np
a = [1, 2, 3, 4]
print("Оригинальный массив ")
print(a)
print("Повторяя 2 раза ")
x = np.tile(a, 2)
print(x)
print("Повторяя 3 раза ")
x = np.tile(a, 3)
print(x)

Оригинальный массив 
[1, 2, 3, 4]
Повторяя 2 раза 
[1 2 3 4 1 2 3 4]
Повторяя 3 раза 
[1 2 3 4 1 2 3 4 1 2 3 4]


35

In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print("6 строк и 0 столбцов ")
print(x.shape)
y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 строки и 3 столбца ")
print(y)
x = np.array([1,2,3,4,5,6,7,8,9])
print("Изменить форму массива на (3, 3) -> 3 строки и 3 столбца  ")
x.shape = (3, 3)
print(x)

6 строк и 0 столбцов 
(6,)
(3, 3) -> 3 строки и 3 столбца 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Изменить форму массива на (3, 3) -> 3 строки и 3 столбца  
[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [ ]:
import numpy as np
x = np.linspace(2.5, 6.5, 30)
print(x)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


55

In [ ]:
import numpy as np
x = 10
print("Просматривайте входные данные как массивы как минимум с двумя измерениями:")
print(np.atleast_1d(x))
x = np.arange(4.0).reshape(2, 2)
print(np.atleast_1d(x))
print("Просматривайте входные данные как массивы как минимум с тремя измерениями:")
x =15
print(np.atleast_3d(x))
x = np.arange(3.0)
print(np.atleast_3d(x))

Просматривайте входные данные как массивы как минимум с двумя измерениями:
[10]
[[0. 1.]
 [2. 3.]]
Просматривайте входные данные как массивы как минимум с тремя измерениями:
[[[15]]]
[[[0.]
  [1.]
  [2.]]]


65

In [ ]:
import numpy as np
x = np.array([[1.12, 2.0, 3.45], [2.33, 5.12, 6.0]], float) 
print("Original array:")
print(x)
print(2 in x)
print(0 in x)
print(6 in x)
print(2.3 in x)
print(5.12 in x)

Original array:
[[1.12 2.   3.45]
 [2.33 5.12 6.  ]]
True
False
True
False
True


75

In [ ]:
import numpy as np
x = np.zeros((3,), dtype=('i4,f4,a40'))
new_data = [(1, 2., "Albert Einstein"), (2, 2., "Edmond Halley"), (3, 3., "Gertrude B. Elion")]
x[:] = new_data
print(x)


[(1, 2., b'Albert Einstein') (2, 2., b'Edmond Halley')
 (3, 3., b'Gertrude B. Elion')]


85

In [ ]:
import numpy as np
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])
print(np.append(x, y, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


95

In [ ]:
import numpy as np
x = np.array([2, 3])
y = np.array([])
# size 2, array is not empty
print(x.size)
# size 0, array is empty
print(y.size)

2
0


105

In [ ]:
import numpy as np
nums = np.array([10, 20, 20, 20, 20, 0, 20, 30, 30, 30, 0, 0, 20, 20, 0])
print("Original array:")
print(nums)
print(np.count_nonzero(nums == 10))
print(np.count_nonzero(nums == 20))
print(np.count_nonzero(nums == 30))
print(np.count_nonzero(nums == 0))

Original array:
[10 20 20 20 20  0 20 30 30 30  0  0 20 20  0]
1
7
3
4


115

In [ ]:
import numpy as np
nums = np.array([1,0,2,0,3,0,4,5,6,7,8])
print(" Исходный массив:")
print(nums)
print("Индексы элементов равны нулю указанного массива:")
result = np.where(nums == 0)[0]
print(result)

 Исходный массив:
[1 0 2 0 3 0 4 5 6 7 8]
Индексы элементов равны нулю указанного массива:
[1 3 5]


125

In [ ]:
import numpy as np    
p = np.array([[0], [10], [20]]) 
q= np.array([10, 11, 12]) 
print("Оригинальные массивы:")
print("Массив-1")
print(p)
print("Массив-2")
print(q)
print("Новый массив:")
new_array1 = p + q 
print(new_array1)

Оригинальные массивы:
Массив-1
[[ 0]
 [10]
 [20]]
Массив-2
[10 11 12]
Новый массив:
[[10 11 12]
 [20 21 22]
 [30 31 32]]


135

In [ ]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print(" Исходный массив:")
print(arra_data)
print("Извлеченные данные: второй ряд")
print(arra_data[1,:])

 Исходный массив:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Извлеченные данные: второй ряд
[4 5 6 7]


145

In [ ]:
import numpy as np
arra_data = np.arange(0,36).reshape((6, 6))
print("Исходный массив:")
print(arra_data)
print("Извлеченные данные: первый, третий и пятый элементы третьего и пятого рядов")
print(arra_data[2::2, ::2]) 

Исходный массив:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
Извлеченные данные: первый, третий и пятый элементы третьего и пятого рядов
[[12 14 16]
 [24 26 28]]


155

In [ ]:
import numpy as np
num = np.arange(20)
arr1 = np.reshape(num, [4, 5])
print(" Исходный массив:")
print(arr1)
print([0, 1, 2, 3, 4] in arr1.tolist())
print([0, 1, 2, 3, 5] in arr1.tolist())
print([15, 16, 17, 18, 19] in arr1.tolist())

 Исходный массив:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
True
False
True


Линейная алгебра

5

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([0,1,0])
print(" Оригинальные 1-й массивы:")
print(a)
print(b)
result =  np.einsum("n,n", a, b)
print("Соглашение Эйнштейна о суммировании указанных массивов:")
print(result)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Оригинал Высшее измерение:")
print(x)
print(y)
result = np.einsum("mk,kn", x, y)
print("Соглашение Эйнштейна о суммировании указанных массивов:")
print(result)

 Оригинальные 1-й массивы:
[1 2 3]
[0 1 0]
Соглашение Эйнштейна о суммировании указанных массивов:
2
Оригинал Высшее измерение:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Соглашение Эйнштейна о суммировании указанных массивов:
[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]


15

In [ ]:
import numpy as np
m = np.arange(6).reshape(2,3)
print(" Исходная матрица:")
print(m)
result =  np.trace(m)
print("Номер условия указанной матрицы:")
print(result)

 Исходная матрица:
[[0 1 2]
 [3 4 5]]
Номер условия указанной матрицы:
4


Случайные упражнения

5

In [2]:
import numpy as np
x = np.random.rand(10, 4)
print("Исходный массив: ")
print(x)
y= x[:5, :]
print("Первые 5 строк вышеуказанного массива: ")
print(y)

Исходный массив: 
[[5.78005790e-01 2.96255130e-01 1.46307638e-01 7.88426015e-04]
 [8.00464328e-01 3.17191220e-02 4.32147803e-01 5.90670498e-01]
 [7.06214970e-01 2.30540676e-01 7.17008372e-01 8.61982764e-01]
 [3.05925391e-01 8.44423258e-01 3.62719432e-01 6.58193476e-01]
 [4.17123857e-02 8.91274704e-01 9.18628207e-01 4.78246802e-01]
 [8.26369941e-01 3.44527212e-02 5.37990651e-01 1.40141730e-01]
 [4.19932940e-01 6.94417099e-02 1.74520688e-02 8.42017562e-01]
 [9.68077241e-02 9.86417812e-01 9.71447385e-01 4.30271959e-01]
 [1.96978544e-01 8.15718043e-01 1.76597299e-01 7.33536456e-01]
 [3.99156809e-02 1.47237486e-01 8.28768032e-01 2.67151705e-01]]
Первые 5 строк вышеуказанного массива: 
[[5.78005790e-01 2.96255130e-01 1.46307638e-01 7.88426015e-04]
 [8.00464328e-01 3.17191220e-02 4.32147803e-01 5.90670498e-01]
 [7.06214970e-01 2.30540676e-01 7.17008372e-01 8.61982764e-01]
 [3.05925391e-01 8.44423258e-01 3.62719432e-01 6.58193476e-01]
 [4.17123857e-02 8.91274704e-01 9.18628207e-01 4.78246802e-

15

In [3]:
import numpy as np
x = np.arange(100)
print("Исходный массив:")
print(x)
a = np.random.uniform(0,100)
print("Значение для сравнения:")
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

Исходный массив:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Значение для сравнения:
7.575514881394518
8


Сортировка и поиск упражнений

5

In [4]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print(" Исходный массив:")
print(student_id)
i = np.argsort(student_id)
print("Индексы отсортированных элементов данного массива:")
print(i)

 Исходный массив:
[1023 5202 6230 1671 1682 5241 4532]
Индексы отсортированных элементов данного массива:
[0 3 4 6 1 5 2]


Математические упражнения

5

In [5]:
import numpy as np
x = np.arange(7)
print(" Оригинальный массив ")
print(x)
print("Элементы первого массива возводятся в степени из второго массива поэлементно:")
print(np.power(x, 3))

 Оригинальный массив 
[0 1 2 3 4 5 6]
Элементы первого массива возводятся в степени из второго массива поэлементно:
[  0   1   8  27  64 125 216]


15

In [6]:
import numpy as np
x = [[1, 0], [1, 1]]
y = [[3, 1], [2, 2]]
print("Матрицы и векторы. ")
print("x:")
print(x)
print("y:")
print(y)
print("Матричное произведение двух вышеупомянутых массивов: ")
print(np.matmul(x, y))

Матрицы и векторы. 
x:
[[1, 0], [1, 1]]
y:
[[3, 1], [2, 2]]
Матричное произведение двух вышеупомянутых массивов: 
[[3 1]
 [5 3]]


25

In [7]:
import numpy as np
x = np.array([-1., 0, 1.])
print(np.sinh(x))
print(np.cosh(x))
print(np.tanh(x))

[-1.17520119  0.          1.17520119]
[1.54308063 1.         1.54308063]
[-0.76159416  0.          0.76159416]


35

In [8]:
import numpy as np
x = np.array([1e-99, 1e-100])
print(" Исходный массив: ")
print(x)
print("Натуральный логарифм одного плюс каждого элемента:")
print(np.log1p(x))

 Исходный массив: 
[1.e-099 1.e-100]
Натуральный логарифм одного плюс каждого элемента:
[1.e-099 1.e-100]


Статистические упражнения


5

In [9]:
import numpy as np
x = np.arange(12).reshape((2, 6))
print(" Исходный массив:")
print(x)
r1 =  np.median(x)
print("Медиана указанного массива:")
print(r1)

 Исходный массив:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Медиана указанного массива:
5.5


Упражнения DateTime

5

In [10]:
import numpy as np
print(" Первый понедельник мая 2017 года:    ")
print(np.busday_offset('2017-05', 0, roll='forward', weekmask='Mon'))

 Первый понедельник мая 2017 года:    
2017-05-01


Струнные упражнения

5

In [12]:
import numpy as np
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.join(" ", x)
print(r)

Original Array:
['python exercises' 'PHP' 'java' 'C++']
['p y t h o n   e x e r c i s e s' 'P H P' 'j a v a' 'C + +']


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


15

In [14]:
import numpy as np
x1 = np.array(['Python', 'PHP', 'JS', 'examples', 'html'], dtype=np.str)
print("Оригинальный массив:")
print(x1)
print("Количество 'P':")
r = np.char.count(x1, "P")
print(r)

Оригинальный массив:
['Python' 'PHP' 'JS' 'examples' 'html']
Количество 'P':
[1 2 0 0 0]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  
